{% set name = "google-cloud-videointelligence" %}
{% set version = "2.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google_cloud_videointelligence-{{ version }}.tar.gz
  sha256: 0008b4e618e3ea835883e032d8660c86c6b933c98fe0bfadda036086ff037284

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    # excluding python 3.14 for now because we don't have the required grpcio on conda-forge
    - python >={{ python_min }},<3.14
    - google-api-core >=1.34.1,<3.0.0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0,!=2.24.0,!=2.25.0
    # using looser constraint because we can't support the python >=3.14 constraint
    - grpcio >=1.33.2,<2.0.0
    # more restrictive version for python 3.13
    - proto-plus >=1.25.0,<2.0.0
    - protobuf >=3.20.2,<7.0.0,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - grpc
    - google.cloud.videointelligence
    - google.cloud.videointelligence_v1
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-videointelligence
  summary: Google Cloud Videointelligence API client library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: "Google Cloud Video Intelligence API is a Google Cloud service that makes videos searchable, and discoverable, by extracting metadata with an easy to use API. You can now search every moment of every video file in your catalog and find every occurrence as well as its significance. It quickly annotates videos
    stored in Google Cloud Storage, and helps you identify key nouns entities of your video, and when they occur within the video. Separate signal from noise, by retrieving relevant information at the video, shot or per frame.\nSee the [quick start guide](https://googleapis.dev/python/videointelligence/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/videointelligence/latest/index.html
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-videointelligence

extra:
  recipe-maintainers:
    - xylar
    - parthea
